application:
  name: a-nodeapp
  project: qo-test
  publicly_accessible: true
  organization: QoveryCommunity
routers:
- name: main
  routes:
  - application_name: a-nodeapp
    paths:
    - /
databases:
- type: postgresql # database type
  version: "11.5" # database version
  name: my-db # database name (must be unique)
